[View in Colaboratory](https://colab.research.google.com/github/VictorPetch/MachineLearning/blob/master/Svm_Rbf_Multiclass_Concertado.ipynb)

In [0]:
 # Support Vector Machine (SVM)
# from https://www.superdatascience.com/machine-learning/ 


# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import svm,metrics




In [76]:
import os
import tarfile
from six.moves import urllib

FILE_TO_DOWNLOAD =  "data.csv"
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/willcribeiro/Autonomous-Robot/master/"
DATA_PATH = "Dados/"
DATA_URL = DOWNLOAD_ROOT + DATA_PATH + FILE_TO_DOWNLOAD

def fetch_data(data_url=DATA_URL, data_path=DATA_PATH, file_to_download=FILE_TO_DOWNLOAD):
  if not os.path.isdir(data_path):
    os.makedirs(data_path)
  urllib.request.urlretrieve(data_url, data_path+file_to_download)
  
  
fetch_data()

# observando se o diretório datasets foi criado com sucesso 
#!ls dados
!cat dados/dados.csv

a20,a40,a60,a80,a100,a120,a140,a160,coman2o
51,51,51,26,51,26,18,51,2
51,51,51,51,51,14,16,51,2
51,51,35,51,51,51,21,51,2
51,51,51,51,51,51,23,51,2
51,51,51,51,51,24,21,37,2
51,51,51,51,51,23,23,51,2
51,51,51,51,51,23,24,51,2
51,51,51,51,51,27,51,51,2
51,51,51,51,51,30,51,51,2
51,51,51,51,51,31,30,51,2
51,51,51,51,51,51,28,51,2
51,51,51,51,51,51,28,28,2
51,51,51,51,51,51,26,51,2
51,51,51,51,51,31,35,51,2
51,51,51,51,30,36,35,51,2
51,51,51,33,51,37,36,51,2
51,51,32,51,51,40,39,51,2
51,51,51,51,51,51,33,51,2
51,51,51,51,51,28,51,51,2
51,51,51,51,29,51,51,51,2
51,51,51,51,51,51,39,36,2
51,51,51,29,51,51,39,38,2
51,51,29,51,51,51,39,40,2
51,27,51,51,51,51,39,51,2
51,51,51,51,51,51,34,40,2
51,51,51,51,51,27,51,51,2
51,51,51,28,51,51,51,51,2
51,51,26,51,51,51,37,51,2
51,36,51,51,51,51,38,35,2
51,51,51,51,51,39,26,51,2
51,51,51,51,51,28,38,51,2
51,51,51,51,38,51,51,51,2
51,51,51,51,51,51,51,51,2
51,51,51,51,51,51,51,51,2
51,51,51,51,51,34,51,51,2
51,51,51,51,28,51,51,51,2
51,51,51,27,51,51,51

In [77]:
# Importing the dataset
dataset = pd.read_csv(DATA_PATH+FILE_TO_DOWNLOAD)


dataset.head(  )
#dataset.describe()
#dataset.tails()
print(len(dataset.columns))

8


In [0]:
# Alocando os dados 
# Separando os dados para as variáveis independentes e para variável dependete 

X = dataset.iloc[:,:len(dataset.columns)-1].values
y = dataset.iloc[:, len(dataset.columns)-1].values





In [0]:
from sklearn.model_selection import train_test_split

# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)




In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [0]:
# Fitting SVM to the Training set
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix

#classifier = SVC(kernel = 'linear', random_state = 0)
#Descrevendo o range de C e gamma
C_range = np.logspace(-2, 10, 13)
gamma_range = np.logspace(-9, 3, 13)

Erros=[]
for C in C_range:
  for gamma in gamma_range:
    classifier = svm.SVC(C = C,gamma=gamma)
    classifier.fit(X_train, y_train)

    # Predicting the Test set results
    y_pred = classifier.predict(X_test)
    
    # Making the Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    #print(cm)
    Matrix_error = cm.item(1)+cm.item(2)+cm.item(3)+cm.item(5)+cm.item(6)+cm.item(7)
    Erros.append((C,gamma,Matrix_error))
    
    


In [82]:
#Sort dos dados
#print(len(classifiers))
Erros.sort(key=lambda x:x[2], reverse=False)
#y_pred eh o ultimo y_pred calculado

#print("y_pred:     ",y_pred[:])
#print("y_test:     ",y_test[:])
#print("y_train:    ", y_train[:])
 
#Treinamento com melhor C e gamma

classifier = svm.SVC(C=Erros[0][0],gamma=Erros[0][1])
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
#print("best_y_pred:",y_pred[:])
print("melhor C:",Erros[0][0])
print("melhor gamma:",Erros[0][1])
#print("mean_squared_error:", mean_squared_error(y_pred,y_test) )
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(Erros)




melhor C: 1000.0
melhor gamma: 0.1
[[29  1  1]
 [ 3 22  3]
 [ 1  2 18]]
[(1000.0, 0.1, 11), (1.0, 0.1, 14), (10.0, 0.01, 14), (10.0, 1.0, 14), (100.0, 1.0, 14), (10000.0, 0.01, 14), (10000.0, 0.1, 14), (100000.0, 0.001, 14), (100000.0, 0.01, 14), (1000.0, 1.0, 15), (10000000.0, 0.001, 15), (100000000.0, 0.01, 15), (1000.0, 0.001, 16), (10000.0, 0.001, 16), (1000000.0, 0.0001, 16), (10000000.0, 0.0001, 16), (10000000.0, 0.01, 16), (1000000000.0, 0.01, 16), (10000000000.0, 1e-08, 16), (10000000000.0, 1e-06, 16), (10000000000.0, 0.01, 16), (1.0, 1.0, 17), (10.0, 0.1, 17), (100.0, 0.001, 17), (100.0, 0.01, 17), (10000.0, 0.0001, 17), (100000.0, 1e-05, 17), (100000.0, 0.1, 17), (1000000.0, 1e-07, 17), (1000000.0, 1e-06, 17), (1000000.0, 1e-05, 17), (1000000.0, 0.001, 17), (1000000.0, 0.01, 17), (10000000.0, 1e-07, 17), (10000000.0, 1e-06, 17), (100000000.0, 1e-07, 17), (100000000.0, 1e-06, 17), (1000000000.0, 1e-07, 17), (1000000000.0, 1e-06, 17), (1000000000.0, 0.0001, 17), (10000000000.0,

In [83]:
# Visualising the Training set results
from matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
#print(classifier.predict(np.array([X1.ravel(), X2.ravel()]).T))

plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('blue', 'green', 'magenta')))

plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('blue', 'green', 'magenta'))(i), label = j)
plt.title('SVM (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

ValueError: ignored

[[1 2 3]
 [2 3 4]]
[[1 2 3]
 [2 3 4]
 [7 8 9]]


[[0, 3, 4], [1, 2]]

[[5 6 1]
 [3 1 6]
 [8 0 0]]
3
