[View in Colaboratory](https://colab.research.google.com/github/VictorPetch/MachineLearning/blob/master/Svm_Rbf_Multiclass.ipynb)

In [0]:
# Support Vector Machine (SVM)
# from https://www.superdatascience.com/machine-learning/ 


# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import svm,metrics



In [2]:
import os
import tarfile
from six.moves import urllib

FILE_TO_DOWNLOAD =  "dados.csv"
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/VictorPetch/MachineLearning/master/"
DATA_PATH = "dados/"
DATA_URL = DOWNLOAD_ROOT + DATA_PATH + FILE_TO_DOWNLOAD

def fetch_data(data_url=DATA_URL, data_path=DATA_PATH, file_to_download=FILE_TO_DOWNLOAD):
  if not os.path.isdir(data_path):
    os.makedirs(data_path)
  urllib.request.urlretrieve(data_url, data_path+file_to_download)
  
  
fetch_data()

# observando se o diretório datasets foi criado com sucesso 
!ls dados
#!cat dados/dados.csv

dados.csv


In [3]:
# Importing the dataset
dataset = pd.read_csv(DATA_PATH+FILE_TO_DOWNLOAD)


dataset.head(  )
#dataset.describe()
#dataset.tails()

a20  a40  a60  a80  a100  a120  a140  a160  coman2o
0   51   51   51   26    51    26    18    51        2
1   51   51   51   51    51    14    16    51        2
2   51   51   35   51    51    51    21    51        2
3   51   51   51   51    51    51    23    51        2
4   51   51   51   51    51    24    21    37        2

Shuffle e alocando os dados

In [4]:
# Misturando os dados 

from sklearn.utils import shuffle



# Separando os dados para as variáveis independentes e para variável dependete 

X = shuffle(dataset.iloc[:,:].values) 
y = shuffle(dataset.iloc[:, 8].values) 
print(y[:])
#X = X[:,[0,1,2]]  escolhendo colunas específicas de X

#Dividindo entre arquivos de treinamento e teste 
#Split the data into training/testing sets
#X_train = X[:-25]
#X_test = X[-25:]
#Split the targets into training/testing sets
#y_train = y[:-25]
#y_test = y[-25:]

#X = dataset.iloc[30:60,5:7].values
#y = dataset.iloc[30:60,8].values
#print(y[:])


[1 0 1 2 1 2 0 2 1 2 1 1 1 2 1 0 0 2 1 0 2 1 2 2 0 2 2 1 1 0 1 1 0 0 0 1 2
 1 2 2 2 1 0 1 1 0 2 2 0 1 2 2 1 0 1 0 1 1 1 0 1 2 2 1 2 1 2 1 1 2 0 1 1 0
 1 1 1 0 1 2 0 1 2 2 1 2 1 2 2 0 0 0 0 2 0 2 2 2 0 2 1 2 2 0 1 2 1 2 2 1 1
 1 1 0 2 2 0 1 0 2 0 1 1 0 1 1 2 1 2 2 0 1 0 0 2]


In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.05, random_state = 2)

In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [0]:
# Fitting SVM to the Training set
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error

#classifier = SVC(kernel = 'linear', random_state = 0)
#Descrevendo o range de C e gamma
C_range = np.logspace(-2, 10, 13)
gamma_range = np.logspace(-9, 3, 13)
classifiers = []
for C in C_range:
  for gamma in gamma_range:
    classifier = svm.SVC(decision_function_shape='ovo',C=C, gamma=gamma)
    """"Pipeline((
    ("scaler", StandardScaler()),
    ("svm_clf", SVC(decision_function_shape='ovo'))
    ))"""""
    classifier.fit(X_train, y_train)

    # Predicting the Test set results

    y_pred = classifier.predict(X_test)
    classifiers.append((C,gamma,mean_squared_error(y_pred,y_test)))
    
    


    


In [8]:
#print(len(classifiers))
classifiers.sort(key=lambda x:x[2], reverse=False)
print(classifiers)
print(y_test[:])
print(y_pred[:])




[(1000000000.0, 1e-08, 0.42857142857142855), (10000000000.0, 1e-08, 0.42857142857142855), (0.01, 1e-09, 0.5714285714285714), (0.01, 1e-08, 0.5714285714285714), (0.01, 1e-07, 0.5714285714285714), (0.01, 1e-06, 0.5714285714285714), (0.01, 1e-05, 0.5714285714285714), (0.01, 0.0001, 0.5714285714285714), (0.01, 0.001, 0.5714285714285714), (0.01, 0.01, 0.5714285714285714), (0.01, 0.1, 0.5714285714285714), (0.01, 1.0, 0.5714285714285714), (0.01, 10.0, 0.5714285714285714), (0.01, 100.0, 0.5714285714285714), (0.01, 1000.0, 0.5714285714285714), (0.1, 1e-09, 0.5714285714285714), (0.1, 1e-08, 0.5714285714285714), (0.1, 1e-07, 0.5714285714285714), (0.1, 1e-06, 0.5714285714285714), (0.1, 1e-05, 0.5714285714285714), (0.1, 0.0001, 0.5714285714285714), (0.1, 0.001, 0.5714285714285714), (0.1, 0.01, 0.5714285714285714), (0.1, 0.1, 0.5714285714285714), (0.1, 1.0, 0.5714285714285714), (0.1, 10.0, 0.5714285714285714), (0.1, 100.0, 0.5714285714285714), (0.1, 1000.0, 0.5714285714285714), (1.0, 1e-09, 0.571428

In [9]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[0 1 0]
 [0 3 0]
 [1 2 0]]


In [10]:
# Visualising the Training set results
from matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
#print(classifier.predict(np.array([X1.ravel(), X2.ravel()]).T))

plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('blue', 'green', 'magenta')))

plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('blue', 'green', 'magenta'))(i), label = j)
plt.title('SVM (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

ValueError: ignored

In [236]:
import numpy as np
a = np.array([[1,2,3], [2,3,4]])
print(a) 
a = np.vstack([a, [7,8,9]])
print(a)



[[1 2 3]
 [2 3 4]]
[[1 2 3]
 [2 3 4]
 [7 8 9]]
